baseURL = "https://vaishnavm217.github.io"
languageCode = "en-us"
title = "My Website"
theme = 'black-and-light'

paginate = 10
pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  avatarurl = "images/avatar.jpg"
  sitename = "Vaishnav Murali"
  [[params.social]]
      name = "Github"
      icon = "fab fa-github"
      url = "https://github.com/vaishnavm217"
      weight = 2

  [[params.social]]
      name = "Telegram"
      icon = "fab fa-telegram"
      url = "https://t.me/@AlphaV"
      weight = 3

  [[params.social]]
      name = "Email"
      icon = "fab fa-google"
      url = "mailto:resume-mails@randomdomain.anonaddy.me"
      weight = 1

[[menu.main]]
    name = "About"
    url  = "/"
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
[[menu.main]]
    name = "Resume"
    url  = "/pdf/resume.pdf"
